install: skip
sudo: false
language: generic
services:
- docker
env:
- appslist=appslist
install:
- gem install travis
- docker run -d --name ct -v $PWD:/srv -v /dev:/dev -v /sys:/sys --privileged --cap-add=ALL -w /srv alpine:edge /bin/sleep 36000
- docker exec ct ./prepare.sh
script:
- |
  source functions.sh
  echo 00
  user=untoreh
  repo_rem=untoreh/trees
  repo_rem_url="https://${GIT_USER}:${GIT_TOKEN}@github.com/$repo_rem"
  ## tags format is ${PKG}-YY.MM-X
  PKG=${TRAVIS_TAG/-*}
  if [ -n "$PKG" ]; then
    BAS=$(cat $appslist | grep "$PKG" | head -1 | sed 's/.*://')
  fi
  ## skip build if 
  ## - the tag was not pushed by base repo (to rebuild all the dependents)
  ## - pkg is already built on the latest base
  ## - it is not older than 1 week
  echo 0
  pkg_d=$(last_release_date $repo_rem $PKG)
  echo 01
  bas_d=$(last_release_date $user/$BAS)
  echo 02
  week_old=$(release_older_than $pkg_d "7 days ago")
  echo 03
  set -x
  if [ "$PKG" != "$BAS" -a $bas_d -le $pkg_d -a ! "$week_old" ]; then
    printc "$PKG was recently built."
    TRAVIS_JOB_NUMBER=${TRAVIS_JOB_NUMBER:-$TRAVIS_BUILD_NUMBER}
    travis cancel $TRAVIS_JOB_NUMBER --no-interactive -t $TRAVIS_TOKEN
    echo skip1
    sleep 3600
  fi
  set +x
  echo 1
  ## if the tag is a base, retag for each app beloning to such base and exit
  ## if there is no prefix (both PKG and BAS are empty) all apps get retagged (grep "")
  if [ "$PKG" = "$BAS" ]; then
    for a in $(cat $appslist | grep "$BAS"); do
      newtag=$(md)
      pkg_dep=${a/:*/}
      git tag ${pkg_dep}-${newtag} && git push origin --tags
    done
    travis cancel $TRAVIS_JOB_NUMBER --no-interactive -t $TRAVIS_TOKEN
    echo skip2
    sleep 3600
  fi
  echo 2
  ## if the event is a cron or commit is not app-prefixed we push a new tag for each app and exit
  if [ "$TRAVIS_EVENT_TYPE" = cron -a -z "$PKG" ]; then
    newtag=$(md)
    for a in $(cat $appslist); do
      newtag=$(md)
      pkg_dep=${a/:*/}
      git tag ${pkg_dep}-${newtag} && git push origin --tags
    done
    travis cancel $TRAVIS_JOB_NUMBER --no-interactive -t $TRAVIS_TOKEN
    echo skip3
    sleep 3600
  fi
  echo 3
- docker exec ct ./run.sh $PKG
- |
  ## if no changes where made to the tree skip deployment
  if [ $(cat file.up | grep "$PKG") ]; then
    travis cancel $TRAVIS_JOB_NUMBER --no-interactive -t $TRAVIS_TOKEN
    sleep 3600
  fi
deploy:
  provider: releases
  api_key:
    secure: RkWrNY2ej0d1f25BQTySI6lAqQJYPWQeHmns4B6QdFAG0LZveh02mGVBY9Jf+GzKM2+B/kFjCbLbCReeRfZ+rp3+0xwjMmRgCiaP76Ru5VpJ78obZXOwEFVU9NEIptqrxTK5GsXLuKIva3jN65sY4R89VPlnyS+WDHP3USnVD9WEPfvZ4yCRKVpVQSlffY3FhNHkE76RDjZbouVifldEmzjUNCTjpPYJEK/26cYPpZv4Y1usZV20XBckn1JTLHKYCqFw4NQEej5pp8FeUVoaY45hupj7XMsSEEyjqGjwi1HBKXZDMO5j0w7RuFF0PU2HdHiQgQuG4ejDuDz/Tj7UDRcDs6+AHjNk+hyEb2Y0ywrXoLqtAyEU0tD0Lr/m/77dmJogADpqt744VZCYD9fprE45m+DfiVnCiBE2w0eQ6sOShzefqfJPu1QrhXjoCsjsHx6lQuZx5otx1BFtYjST5NtpDuwtFmfkIz+mE7ySYG2tw9W99xcwqN277lc1sVDErkCb6XUhZv6A6nO79QZ9RWMG1MB0xdJsip2B1IRdcIaZw+6TMR5Cxa3tZVwA+KeVu8DbfDfkuDR3G29/fkaA7jQL7gDZxd6LbD41N/RsYqU2OFRSQ6D6cMKzGvA0X3RVJe61yReLOCDy4feJC5iOfWcmeWOASOAut6Me1DQdycY=
  skip_cleanup: true
  file_glob: true
  file:
  - "${PKG}.tar"
  - "${PKG}.sum"
  on:
    tags: true
after_deploy:
  - |
    ## since a build has been deployed update the static tag
    git symbolic-ref refs/tags/${PKG} refs/tags/$TRAVIS_TAG
    git push --tags
    fetch_artifact github/hub:2.3.0-pre9 "linux-amd64.*.tgz" $PWD
    GITHUB_TOKEN=$GIT_TOKEN
    hub*/bin/hub release edit "$TRAVIS_TAG" -m "" "${PKG}"