#!/bin/bash

source functions.sh

rem_repo="untoreh/trees"
repo_path=$(./fetch-alp-tree.sh | tail -1)
repo_local="${PWD}/lrepo"
ref="trunk"
pkg="etcd"

## copy repo to local filesystem to allow checkout through hardlinks
rm -rf $repo_local
cp -a $repo_path $repo_local

## build app tree
prepare_rootfs ${pkg}
apkc ${pkg} add ${pkg}
wrap_rootfs ${pkg}

## commit tree to app branch
rev=$(ostree --repo=${repo_local} commit -s "$(date)-${pkg}-build"  \
     --skip-if-unchanged -b ${pkg} ${pkg})

## get the last app checksum from remote
old_csum=$(fetch_artifact $rem_repo ${pkg}.sum -)
## get checksum of committed branch
new_csum=$(ostree --repo=${repo_local} ls ${pkg} -Cd | awk '{print $5}')
## end if unchanged
compare_csums

## create delta of app branch
ostree --repo=${repo_local} static-delta generate --from=${ref} ${pkg}  \
    --inline --min-fallback-size 0 --filename=${rev}

## checksum and compress
echo $new_csum >${pkg}.sum
tar cvf ${pkg}.tar ${rev}
