#!/bin/bash

source functions.sh

rem_repo="untoreh/trees"
repo_path=$(./fetch-ubu-tree.sh | tail -1)
ref="trunk"
pkg="hhvm"

## checkout the base
rm -rf ${pkg}
ostree checkout --repo=${repo_path} -H --user-mode ${ref} ${pkg}

## package routines
mount_hw $pkg
alias crc="chroot $pkg"
cp -a /etc/resolv.conf $pkg/etc/
source $pkg/etc/os-release
crc apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x5a16e7281be7a449
crc add-apt-repository "deb http://dl.hhvm.com/ubuntu $UBUNTU_CODENAME main"
crc apt update
crc apt install -y -q hhvm
umount_hw $pkg
wrap_rootfs $pkg

## commit tree to app branch
rev=$(ostree --repo=${repo_path} commit -s "$(date)-${pkg}-build"  \
 --skip-if-unchanged -b ${pkg} ${pkg})

## get the last app checksum from remote
old_csum=$(fetch_artifact $rem_repo ${pkg}.sum -)
## get checksum of committed branch
new_csum=$(ostree --repo=${repo_local} ls ${pkg} -Cd | awk '{print $5}')
## end if unchanged
compare_csums

## create delta of app branch
ostree --repo=${repo_path} static-delta generate --from=${ref} ${pkg}  \
 --inline --min-fallback-size 0 --filename=${rev}

## checksum and compress
ostree checksum ${pkg} > ${pkg}.sum
tar cvf ${pkg}.tar ${rev}
