#!/bin/bash

source functions.sh

rem_repo="untoreh/trees"
repo_path=$(./fetch-ubu-tree.sh | tail -1)
ref="trunk"
pkg="hhvm"

## checkout the base
ostree checkout --repo=${repo_path} -H --user-mode ${ref} ${pkg}

## package routines
mount_hw $pkg
alias crc="chroot $pkg"
source $pkg/etc/os-release
crc apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x5a16e7281be7a449
crc add-apt-repository "deb http://dl.hhvm.com/ubuntu $UBUNTU_CODENAME main"
crc apt update
crc apt install -y -q hhvm
umount_hw $pkg
exit
new_csum=$(ostree checksum ${pkg})
## get the latest app checksum from remote
old_csum=$(fetch_artifact $rem_repo ${pkg}.sum -)

## end if unchanged
if [ "$new_csum" = "$old_csum" ] ; then
    printc "${pkg} already up to update."
    exit
fi
## commit tree to app branch
wrap_rootfs ${pkg}
rev=$(ostree --repo=${repo_local} commit -s "$(date)-${pkg}-build"  \
 --skip-if-unchanged -b ${pkg} ${pkg})

## create delta of app branch
ostree --repo=${repo_local} static-delta generate --from=${ref} ${pkg}  \
 --inline --min-fallback-size 0 --filename=${rev}

## checksum and compress
ostree checksum ${pkg} > ${pkg}.sum
tar cvf delta-${pkg}.tar ${rev}
