#!/bin/bash

source functions.sh

rem_repo="untoreh/trees"
ref="trunk"
pkg="imageproxy"
img_repo="willnorris.com/go/imageproxy/cmd/imageproxy"

## init tree
base_tree

## build app tree
## build imageproxy
install_tools go musl-dev
mkdir -p /go
export GOPATH=/go GOROOT=/usr/lib/go
go get $img_repo
cp /go/bin/${pkg} ${pkg}/${pkg}
chmod +x ${pkg}/${pkg}
copy_image_cfg $pkg
wrap_rootfs ${pkg} -c

## pack the tree
package_tree