#!/bin/bash

source functions.sh

rem_repo="untoreh/trees"
ref="trunk"
pkg="imageproxy"
img_repo="willnorris.com/go/imageproxy/cmd/imageproxy"

## init tree
base_tree none

## build app tree
## build imageproxy
install_tools go musl-dev
go_env
go get $img_repo
cp ${GO_PATH}/bin/${pkg} ${pkg}/${pkg}
chmod +x ${pkg}/${pkg}

copy_image_cfg $pkg
wrap_rootfs ${pkg} -c

## pack the tree
package_tree