#!/bin/bash -x

source functions.sh

rem_repo="untoreh/trees"
repo_path=$(./fetch-ubu-tree.sh | tail -1)
ref="trunk"
pkg="hhvm"
## checkout the base
rm -rf ${pkg}
ostree checkout --repo=${repo_path} -H --user-mode ${ref} ${pkg}-lo
mount_over $pkg

## package routines
mount_hw $pkg
alias crc="chroot $pkg"
cp -a /etc/resolv.conf $pkg/etc/
crc apt-key adv --recv-keys --keyserver hkp://keyserver.ubuntu.com:80 0x5a16e7281be7a449
crc bash -c 'source /etc/os-release ; echo "deb http://dl.hhvm.com/ubuntu $UBUNTU_CODENAME main" > /etc/apt/sources.list.d/hhvm.list'
crc apt update
crc bash -c 'DEBIAN_FRONTEND=noninteractive apt install -y -q hhvm'
crc apt-get clean
crc rm -rf /var/lib/apt/lists/*
copy_image_cfg $pkg
umount_hw $pkg
wrap_rootfs $pkg -c

## commit tree to app branch
rev=$(ostree --repo=${repo_path} commit -s "$(date)-${pkg}-build" \
	--skip-if-unchanged --link-checkout-speedup -b ${pkg} ${pkg})

## get the last app checksum from remote
old_csum=$(fetch_artifact ${rem_repo}:${pkg} ${pkg}.sum -)
## get checksum of committed branch
new_csum=$(ostree --repo=${repo_path} ls ${pkg} -Cd | awk '{print $5}')
## end if unchanged
compare_csums

## create delta of app branch
ostree --repo=${repo_path} static-delta generate --from=${ref} ${pkg} \
	--inline --min-fallback-size 0 --filename=${rev}

## checksum and compress
ostree checksum ${pkg} >${pkg}.sum
tar cvf ${pkg}.tar ${rev}
