#!/bin/bash

source functions.sh

rem_repo="untoreh/trees"
ref="trunk"
pkgs="tidb tidb_ctl"
artifact="tidb-latest-linux-amd64"

## build app trees 
for pkg in $pkgs; do
    base_tree none
done

fetch_artifact http://download.pingcap.org/${artifact}.tar.gz artf -4
for pkg in $pkgs; do
    mkdir -p ${pkg}/usr/bin
    case $pkg in 
    "tidb")
        mv artf/${artifact}/bin/{pd-server,tidb-server,tikv-server} ${pkg}/usr/bin
        ;;
    "tidb_ctl")
        mv artf/${artifact}/bin/{goyacc,pd-ctl,pd-recover,pd-tso-bench,tikv-ctl} ${pkg}/usr/bin
        ;;
    esac
    copy_image_cfg $pkg
    wrap_rootfs $pkg -c
done

## pack
for pkg in $pkgs; do
    package_tree
done